---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=latest update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
   - Start Nginx

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Reload Nginx

- name: Replace Parent Nginx Config
  copy: dest=/etc/nginx/nginx.conf src=templates/nginx.conf owner=root group=root mode=644 backup=yes 
  notify: 
    - Reload Nginx   

- name: Add Site Config
  when: nginxinstalled|success
  template: src={{ domain }}.j2 dest=/etc/nginx/sites-available/{{ domain }} owner=root group=root

- name: Enable Site Config
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify:
    - Reload Nginx

- name: Create Application Directory
  file: path=/var/www/{{ domain }} state=directory mode=775 owner=www-data group=www-data recurse=yes

- name: Install Unzip
  apt: pkg=unzip state=latest update_cache=true