---
- name: Add PPA Repository
  become: yes
  apt_repository: repo={{ php_ppa }}

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PHP
  become: yes
  apt: pkg=php7.0 state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{php_packages}}"
  when: php_packages is defined
  notify:
    - restart php7-fpm

- include: configure.yml