---
- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ php_timezone }}'

- name: disabling opcache cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='opcache.enable_cli='
              line='opcache.enable_cli=0'

# Removes the Zend Opcache 

- name: Remove Redudant OpCache Symlink
  become: yes
  file: dest=/etc/php/7.0/cli/conf.d/20-opcache.ini state=absent
       
